// Preprocess content to fix malformed <mark> tags generated by LLM
export const preprocessMarkdown = (content: string) => {
    if (!content) return '';
    return content.replace(/<mark>([\s\S]*?)<\/mark>/g, (match, inner) => {
        // Fix LLM putting multiple list items on one line
        if (inner.includes(' * ')) {
            inner = inner.split(/(?=\s\*\s)/).map((part: string) => {
                const trimmed = part.trim();
                if (trimmed.startsWith('* ')) {
                    return `\n* ${trimmed.substring(2)}\n`;
                }
                return part;
            }).join('');
        }

        // Split by newline to handle multi-line <mark> blocks
        const lines = inner.split('\n');
        const processedLines = lines.map((line: string) => {
            if (!line.trim()) return line;

            // Extract block prefix (e.g., "# ", "* ", "1. ", "- ")
            const blockMatch = line.match(/^(\s*(?:\*|-|\d+\.|#+)\s+)(.*)$/);
            if (blockMatch) {
                return `${blockMatch[1]}<mark>${blockMatch[2]}</mark>`;
            }

            return `<mark>${line}</mark>`;
        });

        return processedLines.join('\n');
    });
};

export function replaceMermaidBlockAtIndex(
    markdown: string,
    blockIndex: number,
    newCode: string
): string | null {
    const mermaidBlockPattern = /```mermaid(?:[ \t].*)?\n[\s\S]*?```/g;
    const matches = Array.from(markdown.matchAll(mermaidBlockPattern));
    const target = matches[blockIndex];
    if (!target || target.index === undefined) return null;

    const replacement = `\`\`\`mermaid\n${newCode}\n\`\`\``;
    if (replacement === target[0]) return null;

    return `${markdown.substring(0, target.index)}${replacement}${markdown.substring(target.index + target[0].length)}`;
}
