/**
 * Sanitizes Mermaid code generated by LLMs to prevent common rendering errors.
 */

export function sanitizeMermaidCode(code: string): string {
    if (!code) return '';
    let sanitized = code;

    // 1. Remove invisible characters (non-breaking spaces, zero-width spaces)
    sanitized = sanitized.replace(/\u00A0/g, ' ');
    sanitized = sanitized.replace(/\u200B/g, '');

    // 2. Convert <br> variants to Mermaid newlines (\n)
    sanitized = sanitized.replace(/<br\s*\/?>/gi, '\\n');

    // 3. Remove HTML comments if any
    sanitized = sanitized.replace(/<!--[\s\S]*?-->/g, '');

    // 4. Remove other HTML tags that LLMs might hallucinate
    // but ONLY those that look distinctly like HTML/XML elements <foo>...</foo> or self closing formats
    // to avoid killing something like <Generics> inside node text.
    sanitized = sanitized.replace(/<\/?(div|span|p|a|b|i|strong|em|mark)[^>]*>/gi, '');

    // 4. Auto-quote node text containing special characters
    // Special characters in mermaid nodes that require quotes include ( ) [ ] { } < > "
    // We only target unquoted node content: (\w+)\[([^\]"]*[()<>{}"\\][^\]"]*)\]
    sanitized = sanitized.replace(/(\w+)\[([^\]"]*[()<>{}"][^\]"]*)\]/g, '$1["$2"]');

    // 5. Normalize Windows line endings
    sanitized = sanitized.replace(/\r\n/g, '\n');

    // 6. Fix Mermaid timeline specific issues
    // Timeline period cannot contain colon. If LLM generated time like "14:30 : event", we must replace the period's colon.
    if (sanitized.trim().startsWith('timeline')) {
        sanitized = sanitized.replace(/(\d{1,2}):(\d{2})(?=\s*:)/g, '$1点$2分');
    }

    // 7. Fix quadrantChart string labels
    if (sanitized.trim().startsWith('quadrantChart')) {
        sanitized = sanitized
            .replace(/([^\n])\s+(x-axis\s+)/g, '$1\n    $2')
            .replace(/([^\n])\s+(y-axis\s+)/g, '$1\n    $2')
            .replace(/([^\n])\s+(quadrant-[1-4]\s+)/g, '$1\n    $2');

        sanitized = sanitized.split('\n').map((line) => {
            const axisMatch = line.match(/^(\s*[xy]-axis\s+)(?:"([^"]+)"|(.+?))\s+-->\s+(?:"([^"]+)"|(.+))$/);
            if (axisMatch) {
                const left = (axisMatch[2] ?? axisMatch[3]).trim();
                const right = (axisMatch[4] ?? axisMatch[5]).trim();
                return `${axisMatch[1]}"${left}" --> "${right}"`;
            }

            const quadrantMatch = line.match(/^(\s*quadrant-[1-4]\s+)(?!")(.+)$/);
            if (quadrantMatch) {
                return `${quadrantMatch[1]}"${quadrantMatch[2].trim()}"`;
            }

            return line;
        }).join('\n');

        // Enforce quotes around point labels if they are missing
        // 创意A: [0.8, 0.9] -> "创意A": [0.8, 0.9]
        sanitized = sanitized.replace(/^([ \t]*)([^"\n:-]+):\s*(\[.*\])$/gm, '$1"$2": $3');
    }

    // 8. Fix block-beta group syntax frequently produced by LLMs.
    if (sanitized.trim().startsWith('block-beta')) {
        let generatedBlockId = 0;
        sanitized = sanitized
            .split('\n')
            .flatMap((line) => {
                const columnGroupMatch = line.match(/^(\s*)columns\s+(auto|\d+)\s+block\["([^"]+)"\]\s*\{\s*$/);
                if (columnGroupMatch) {
                    generatedBlockId += 1;
                    const [, indent, columns, label] = columnGroupMatch;
                    return [
                        `${indent}columns ${columns}`,
                        `${indent}block_${generatedBlockId}["${label}"]`,
                    ];
                }

                const groupMatch = line.match(/^(\s*)block\["([^"]+)"\]\s*\{\s*$/);
                if (groupMatch) {
                    generatedBlockId += 1;
                    const [, indent, label] = groupMatch;
                    return `${indent}block_${generatedBlockId}["${label}"]`;
                }

                if (/^\s*}\s*$/.test(line)) {
                    return [];
                }

                return line;
            })
            .join('\n');
    }

    return sanitized.trim();
}

/**
 * Aggressive sanitization as a fallback when normal sanitization fails to produce valid syntax.
 * strips complex characters from inside node brackets to ensure basic shape rendering.
 */
export function aggressiveSanitize(code: string): string {
    let sanitized = sanitizeMermaidCode(code);

    // Aggressive: Remove anything that's not alphanumeric, space, or basic punctuation inside brackets
    // Keep it minimal to guarantee parsing
    sanitized = sanitized.replace(/\[(["']?)(.*?)\1\]/g, (match, quote, innerText) => {
        // Strip out any weird symbols that break mermaid parser
        const cleanedText = innerText.replace(/[^a-zA-Z0-9\u4e00-\u9fa5\s\-_.,]/g, '');
        return `["${cleanedText}"]`; // Force quotes around cleaned text
    });

    return sanitized;
}
