/**
 * Sanitizes Mermaid code generated by LLMs to prevent common rendering errors.
 */

export function sanitizeMermaidCode(code: string): string {
    if (!code) return '';
    let sanitized = code;

    // 1. Remove invisible characters (non-breaking spaces, zero-width spaces)
    sanitized = sanitized.replace(/\u00A0/g, ' ');
    sanitized = sanitized.replace(/\u200B/g, '');

    // 2. Convert <br> variants to Mermaid newlines (\n)
    sanitized = sanitized.replace(/<br\s*\/?>/gi, '\\n');

    // 3. Remove HTML comments if any
    sanitized = sanitized.replace(/<!--[\s\S]*?-->/g, '');

    // 4. Remove other HTML tags that LLMs might hallucinate
    // but ONLY those that look distinctly like HTML/XML elements <foo>...</foo> or self closing formats
    // to avoid killing something like <Generics> inside node text.
    sanitized = sanitized.replace(/<\/?(div|span|p|a|b|i|strong|em|mark)[^>]*>/gi, '');

    // 4. Auto-quote node text containing special characters
    // Special characters in mermaid nodes that require quotes include ( ) [ ] { } < > "
    // We only target unquoted node content: (\w+)\[([^\]"]*[()<>{}"\\][^\]"]*)\]
    sanitized = sanitized.replace(/(\w+)\[([^\]"]*[()<>{}"][^\]"]*)\]/g, '$1["$2"]');

    // 5. Normalize Windows line endings
    sanitized = sanitized.replace(/\r\n/g, '\n');

    return sanitized.trim();
}

/**
 * Aggressive sanitization as a fallback when normal sanitization fails to produce valid syntax.
 * strips complex characters from inside node brackets to ensure basic shape rendering.
 */
export function aggressiveSanitize(code: string): string {
    let sanitized = sanitizeMermaidCode(code);

    // Aggressive: Remove anything that's not alphanumeric, space, or basic punctuation inside brackets
    // Keep it minimal to guarantee parsing
    sanitized = sanitized.replace(/\[(["']?)(.*?)\1\]/g, (match, quote, innerText) => {
        // Strip out any weird symbols that break mermaid parser
        const cleanedText = innerText.replace(/[^a-zA-Z0-9\u4e00-\u9fa5\s\-_.,]/g, '');
        return `["${cleanedText}"]`; // Force quotes around cleaned text
    });

    return sanitized;
}
