[pytest]
testpaths = backend/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
addopts = -v --tb=short
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

markers =
    unit: 单元测试
    api: API测试
    integration: 集成测试
    e2e: 端到端测试
    slow: 慢速测试（真实 LLM 调用，仅本地运行）
