import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeRaw from 'rehype-raw';
import { useStore, ArtifactVersion } from '../store';
import { Mermaid } from './Mermaid';
import { Download, Code, Eye, History, X } from 'lucide-react';

export const ArtifactPane: React.FC = () => {
  const artifactContent = useStore((state) => state.artifactContent);
  const artifactHistory = useStore((state) => state.artifactHistory);
  const [viewMode, setViewMode] = useState<'preview' | 'code'>('preview');
  const [showHistory, setShowHistory] = useState(false);
  const [selectedVersion, setSelectedVersion] = useState<ArtifactVersion | null>(null);

  const handleDownload = () => {
    const blob = new Blob([artifactContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'lisa_artifact.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const openHistory = () => {
    if (artifactHistory.length > 0) {
      setSelectedVersion(artifactHistory[artifactHistory.length - 1]);
    } else {
      setSelectedVersion(null);
    }
    setShowHistory(true);
  };

  // Preprocess content to fix malformed <mark> tags generated by LLM
  const preprocessMarkdown = (content: string) => {
    if (!content) return '';
    return content.replace(/<mark>([\s\S]*?)<\/mark>/g, (match, inner) => {
      // Fix LLM putting multiple list items on one line inside <mark>
      if (inner.includes(' * ')) {
        inner = inner.split(/(?=\s\*\s)/).map((part: string) => {
          const trimmed = part.trim();
          if (trimmed.startsWith('* ')) {
            return `\n* ${trimmed.substring(2)}\n`;
          }
          return part;
        }).join('');
      }
      
      // Split by newline to handle multi-line <mark> blocks
      const lines = inner.split('\n');
      const processedLines = lines.map(line => {
        if (!line.trim()) return line;
        
        // Extract block prefix (e.g., "# ", "* ", "1. ", "- ")
        const blockMatch = line.match(/^(\s*(?:\*|-|\d+\.|#+)\s+)(.*)$/);
        if (blockMatch) {
          return `${blockMatch[1]}<mark>${blockMatch[2]}</mark>`;
        }
        
        return `<mark>${line}</mark>`;
      });
      
      return processedLines.join('\n');
    });
  };

  const displayContent = preprocessMarkdown(artifactContent);

  const markdownComponents = {
    h1: ({node, ...props}: any) => <h1 className="text-3xl font-bold text-white mb-6 pb-2 border-b border-[#1e293b]" {...props} />,
    h2: ({node, ...props}: any) => <h2 className="text-2xl font-bold text-white mt-8 mb-4 before:content-['#'] before:text-blue-500 before:opacity-50 before:mr-2" {...props} />,
    h3: ({node, ...props}: any) => <h3 className="text-xl font-semibold text-slate-200 mt-6 mb-3" {...props} />,
    p: ({node, ...props}: any) => <p className="mb-4 leading-relaxed text-slate-400" {...props} />,
    ul: ({node, ...props}: any) => <ul className="list-disc pl-6 mb-4 space-y-2 text-slate-400" {...props} />,
    ol: ({node, ...props}: any) => <ol className="list-decimal pl-6 mb-4 space-y-2 text-slate-400" {...props} />,
    li: ({node, ...props}: any) => <li className="leading-relaxed" {...props} />,
    strong: ({node, ...props}: any) => <strong className="font-bold text-white" {...props} />,
    blockquote: ({node, ...props}: any) => <blockquote className="border-l-4 border-blue-500 pl-4 py-2 my-4 bg-blue-500/5 rounded-r text-slate-400 italic" {...props} />,
    table: ({node, ...props}: any) => <div className="overflow-x-auto mb-6"><table className="w-full border-collapse text-sm" {...props} /></div>,
    th: ({node, ...props}: any) => <th className="bg-[#1e293b] text-slate-200 font-semibold text-left p-3 border-b border-[#334155]" {...props} />,
    td: ({node, ...props}: any) => <td className="p-3 border-b border-[#1e293b] text-slate-400 group-hover:bg-white/5" {...props} />,
    tr: ({node, ...props}: any) => <tr className="hover:bg-white/[0.02] transition-colors group" {...props} />,
    mark: ({node, ...props}: any) => <mark className="bg-emerald-500/15 text-emerald-400 px-1.5 py-0.5 rounded font-medium shadow-[0_0_8px_rgba(16,185,129,0.1)] box-decoration-clone" {...props} />,
    code({ node, inline, className, children, ...props }: any) {
      const match = /language-(\w+)/.exec(className || '');
      const language = match ? match[1] : '';
      
      if (!inline && language === 'mermaid') {
        return <Mermaid chart={String(children).replace(/\n$/, '')} />;
      }
      
      return !inline ? (
        <div className="relative my-6 rounded-lg overflow-hidden border border-[#1e293b] bg-[#0f172a]">
          {language && (
            <div className="flex items-center px-4 py-2 bg-[#1e293b] text-xs text-slate-400 font-mono border-b border-[#0f172a]">
              {language}
            </div>
          )}
          <pre className="p-4 overflow-x-auto text-sm font-mono text-slate-300">
            <code className={className} {...props}>
              {children}
            </code>
          </pre>
        </div>
      ) : (
        <code className="bg-white/10 text-blue-300 px-1.5 py-0.5 rounded font-mono text-sm" {...props}>
          {children}
        </code>
      );
    }
  };

  return (
    <section className="flex flex-col w-full lg:w-[60%] bg-[#0B0F17] text-gray-300 relative shadow-2xl overflow-hidden bg-grid-pattern h-full">
      <style>{`
        .bg-grid-pattern {
            background-image: linear-gradient(to right, #1f2937 1px, transparent 1px), linear-gradient(to bottom, #1f2937 1px, transparent 1px);
            background-size: 40px 40px;
            background-color: #0d1117;
        }
        .bg-grid-pattern::before {
            content: "";
            position: absolute;
            inset: 0;
            background: radial-gradient(circle at center, transparent 0%, #0d1117 100%);
            pointer-events: none;
        }
      `}</style>

      <div className="flex items-center justify-between px-6 py-3 border-b border-[#1e293b] bg-[#0d1117]/80 backdrop-blur sticky top-0 z-10 shadow-sm">
        <div className="flex items-center gap-3">
          <div className="p-1 rounded bg-purple-500/10 text-purple-400">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
          </div>
          <div className="flex flex-col">
            <h2 className="text-gray-200 font-semibold text-sm tracking-tight">当前产出物.md</h2>
            <span className="text-[10px] text-slate-500">实时渲染</span>
          </div>
          <span className="ml-2 px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-500 text-[10px] font-medium border border-emerald-500/20 flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
            实时同步
          </span>
        </div>
        <div className="flex items-center gap-1 bg-[#0f172a] p-1 rounded-lg border border-[#1e293b]">
          <button onClick={() => setViewMode('preview')} className={`p-1.5 rounded transition-colors ${viewMode === 'preview' ? 'bg-white/10 text-white' : 'text-slate-400 hover:text-white hover:bg-white/5'}`} title="预览">
            <Eye className="w-4 h-4" />
          </button>
          <button onClick={() => setViewMode('code')} className={`p-1.5 rounded transition-colors ${viewMode === 'code' ? 'bg-white/10 text-white' : 'text-slate-400 hover:text-white hover:bg-white/5'}`} title="代码">
            <Code className="w-4 h-4" />
          </button>
          <div className="w-px h-4 bg-[#1e293b] mx-1"></div>
          <button onClick={openHistory} className="p-1.5 rounded hover:bg-white/10 text-slate-400 hover:text-white transition-colors" title="历史版本">
            <History className="w-4 h-4" />
          </button>
          <button onClick={handleDownload} className="p-1.5 rounded hover:bg-white/10 text-slate-400 hover:text-white transition-colors" title="下载">
            <Download className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-8 md:px-16 relative z-0 custom-scrollbar">
        <div className="max-w-4xl mx-auto pb-20">
          {viewMode === 'preview' ? (
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              rehypePlugins={[rehypeRaw]}
              components={markdownComponents}
            >
              {displayContent}
            </ReactMarkdown>
          ) : (
            <pre className="text-sm font-mono text-slate-300 whitespace-pre-wrap break-words bg-[#0f172a] p-6 rounded-xl border border-[#1e293b]">
              {displayContent}
            </pre>
          )}
        </div>
      </div>

      {showHistory && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm">
          <div className="flex w-full max-w-6xl h-[85vh] overflow-hidden rounded-xl bg-[#0f172a] shadow-2xl ring-1 ring-white/10">
            {/* Sidebar */}
            <div className="w-64 bg-[#0B1120] border-r border-[#1e293b] flex flex-col shrink-0">
              <div className="p-4 border-b border-[#1e293b] flex justify-between items-center">
                <h3 className="text-white font-bold flex items-center gap-2">
                  <History className="w-4 h-4 text-blue-400" />
                  历史版本
                </h3>
                <button onClick={() => setShowHistory(false)} className="text-slate-400 hover:text-white">
                  <X className="w-4 h-4" />
                </button>
              </div>
              <div className="flex-1 overflow-y-auto p-3 space-y-2 custom-scrollbar">
                {artifactHistory.length === 0 ? (
                  <div className="text-slate-500 text-sm text-center mt-10">暂无历史版本</div>
                ) : (
                  [...artifactHistory].reverse().map((v, i) => {
                    const titleMatch = v.content.match(/^#\s+(.+)$/m);
                    const title = titleMatch ? titleMatch[1].trim() : '未命名文档';
                    return (
                      <button
                        key={v.id}
                        onClick={() => setSelectedVersion(v)}
                        className={`w-full text-left px-3 py-2.5 rounded-lg text-sm transition-all ${selectedVersion?.id === v.id ? 'bg-blue-600/20 text-blue-400 border border-blue-500/30 shadow-inner' : 'text-slate-300 hover:bg-white/5 border border-transparent'}`}
                      >
                        <div className="font-medium truncate" title={title}>{title}</div>
                        <div className="flex justify-between items-center mt-1.5">
                          <span className={`text-[10px] px-1.5 py-0.5 rounded font-mono ${selectedVersion?.id === v.id ? 'bg-blue-500/20 text-blue-300' : 'bg-white/10 text-slate-400'}`}>v{artifactHistory.length - i}</span>
                          <span className="text-[10px] opacity-60 font-mono">{new Date(v.timestamp).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</span>
                        </div>
                      </button>
                    );
                  })
                )}
              </div>
            </div>
            
            {/* Main content */}
            <div className="flex-1 flex flex-col bg-[#0B0F17] overflow-hidden relative">
              <div className="px-6 py-3 border-b border-[#1e293b] bg-[#0d1117]/80 backdrop-blur flex items-center justify-between shadow-sm">
                <h2 className="text-gray-200 font-semibold text-sm tracking-tight flex items-center gap-2">
                  <Eye className="w-4 h-4 text-slate-400" />
                  版本预览 <span className="text-slate-500 font-normal">（只读）</span>
                </h2>
              </div>
              <div className="flex-1 overflow-y-auto p-8 md:px-16 custom-scrollbar">
                <div className="max-w-4xl mx-auto pb-20">
                  {selectedVersion ? (
                    <ReactMarkdown
                      remarkPlugins={[remarkGfm]}
                      rehypePlugins={[rehypeRaw]}
                      components={markdownComponents}
                    >
                      {preprocessMarkdown(selectedVersion.content)}
                    </ReactMarkdown>
                  ) : (
                    <div className="flex items-center justify-center h-full text-slate-500">
                      请在左侧选择一个历史版本查看
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </section>
  );
};
